export const FETCH_EXPERIENCE = "EXPERIENCE:FETCH_EXPERIENCE";
export const REQUEST_EXPERIENCE = "EXPERIENCE:REQUEST_EXPERIENCE";
export const SHOW_EXPERIENCE_LOADER = "EXPERIENCE:SHOW_EXPERIENCE_LOADER";
export const HIDE_EXPERIENCE_LOADER = "EXPERIENCE:HIDE_EXPERIENCE_LOADER";
