export const FETCH_PORTFOLIO = "PORTFOLIO:FETCH_PORTFOLIO";
export const REQUEST_PORTFOLIO = "PORTFOLIO:REQUEST_PORTFOLIO";
export const SHOW_PORTFOLIO_LOADER = "PORTFOLIO:SHOW_PORTFOLIO_LOADER";
export const HIDE_PORTFOLIO_LOADER = "PORTFOLIO:HIDE_PORTFOLIO_LOADER";
