export const FETCH_CONTACTS = "CONTACTS:FETCH_CONTACTS";
export const REQUEST_CONTACTS = "CONTACTS:REQUEST_CONTACTS";
export const SHOW_CONTACTS_LOADER = "CONTACTS:SHOW_CONTACTS_LOADER";
export const HIDE_CONTACTS_LOADER = "CONTACTS:HIDE_CONTACTS_LOADER";
