export const FETCH_MOTIVATION = "MOTIVATION:FETCH_MOTIVATION";
export const REQUEST_MOTIVATION = "MOTIVATION:REQUEST_MOTIVATION";
export const SHOW_MOTIVATION_LOADER = "MOTIVATION:SHOW_MOTIVATION_LOADER";
export const HIDE_MOTIVATION_LOADER = "MOTIVATION:HIDE_MOTIVATION_LOADER";
