export const SET_MOTIVATION_PAGE = "MAIN:SET_MOTIVATION_PAGE";
export const SET_CV_PAGE = "MAIN:SET_CV_PAGE";
export const SET_DESKTOP_VERSION = "MAIN:SET_DESKTOP_VERSION";
export const SET_TABLET_VERSION = "MAIN:SET_TABLET_VERSION";
export const SET_MOBILE_VERSION = "MAIN:SET_MOBILE_VERSION";
export const SET_LOW_HEIGHT_VERSION = "MAIN:SET_LOW_HEIGHT_VERSION";
