export const FETCH_ABOUT = "ABOUT:FETCH_ABOUT";
export const REQUEST_ABOUT = "ABOUT:REQUEST_ABOUT";
export const SHOW_ABOUT_LOADER = "ABOUT:SHOW_ABOUT_LOADER";
export const HIDE_ABOUT_LOADER = "ABOUT:HIDE_ABOUT_LOADER";
