export { default as portfolioApi } from "./portfolio";
export { default as aboutApi } from "./about";
export { default as contactsApi } from "./contacts";
export { default as educationApi } from "./education";
export { default as englishApi } from "./english";
export { default as experienceApi } from "./experience";
export { default as motivationApi } from "./motivation";
export { default as skillsApi } from "./skills";
export { default as sendMailApi } from "./sendMail";
