export const FETCH_EDUCATION = "EDUCATION:FETCH_EDUCATION";
export const REQUEST_EDUCATION = "EDUCATION:REQUEST_EDUCATION";
export const SHOW_EDUCATION_LOADER = "EDUCATION:SHOW_EDUCATION_LOADER";
export const HIDE_EDUCATION_LOADER = "EDUCATION:HIDE_EDUCATION_LOADER";
