export const FETCH_SKILLS = "SKILLS:FETCH_SKILLS";
export const REQUEST_SKILLS = "SKILLS:REQUEST_SKILLS";
export const SHOW_SKILLS_LOADER = "SKILLS:SHOW_SKILLS_LOADER";
export const HIDE_SKILLS_LOADER = "SKILLS:HIDE_SKILLS_LOADER";
