export const FETCH_ENGLISH = "ENGLISH:FETCH_ENGLISH";
export const REQUEST_ENGLISH = "ENGLISH:REQUEST_ENGLISH";
export const SHOW_ENGLISH_LOADER = "ENGLISH:SHOW_ENGLISH_LOADER";
export const HIDE_ENGLISH_LOADER = "ENGLISH:HIDE_ENGLISH_LOADER";
